import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { sendEmail } from '@/utils/email';

export async function GET(request) {
  const authHeader = request.headers.get('authorization');
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.NODE_ENV !== 'development') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY
  );

  try {
    const today = new Date().toLocaleDateString('en-CA');
    const tomorrowDate = new Date();
    tomorrowDate.setDate(tomorrowDate.getDate() + 1);
    const tomorrow = tomorrowDate.toLocaleDateString('en-CA');

    // 1. Fetch Today's Appointments
    const { data: todayAppointments, error: todayError } = await supabase
      .from('appointments')
      .select('status, patients(is_high_risk)')
      .eq('appointment_date', today);

    if (todayError) throw todayError;

    // 2. Fetch Tomorrow's Appointments
    const { data: tomorrowAppointments, error: tomorrowError } = await supabase
      .from('appointments')
      .select('time_preference, service_type')
      .eq('appointment_date', tomorrow)
      .in('status', ['Approved']);

    if (tomorrowError) throw tomorrowError;

    // 3. Calculate Operational Metrics
    const totalToday = todayAppointments?.length || 0;
    const completed = todayAppointments?.filter(a => a.status === 'Completed').length || 0;
    const noShows = todayAppointments?.filter(a => a.status === 'No-Show').length || 0;
    
    // Check how many unique high-risk patients were seen today
    const highRiskSeen = todayAppointments?.filter(a => a.patients?.is_high_risk).length || 0;

    const totalTomorrow = tomorrowAppointments?.length || 0;
    const morningTomorrow = tomorrowAppointments?.filter(a => a.time_preference === 'Morning').length || 0;
    const afternoonTomorrow = tomorrowAppointments?.filter(a => a.time_preference === 'Afternoon').length || 0;

    // 4. Send the EOD Email to the Clinic Administrator
    // (We'll use EMAIL_USER as the admin's email for this project)
    const adminEmail = process.env.EMAIL_USER;

    if (adminEmail) {
      await sendEmail({
        to: adminEmail,
        subject: `[EOD Report] Clinic Operations Summary - ${today}`,
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #0f172a; padding: 20px; color: white;">
              <h2 style="margin: 0; font-size: 20px;">AR-JEN Clinic</h2>
              <p style="margin: 5px 0 0 0; color: #94a3b8;">End of Day Operational Report for ${today}</p>
            </div>
            
            <div style="padding: 20px;">
              <h3 style="color: #0f172a; border-bottom: 2px solid #f1f5f9; padding-bottom: 8px;">📊 Today's Performance</h3>
              <ul style="list-style: none; padding: 0; color: #334155; line-height: 1.6;">
                <li><strong>Total Scheduled:</strong> ${totalToday}</li>
                <li><strong>Completed:</strong> <span style="color: #059669; font-weight: bold;">${completed}</span></li>
                <li><strong>No-Shows:</strong> <span style="color: #e11d48; font-weight: bold;">${noShows}</span></li>
                <li><strong>High-Risk Patients Handled:</strong> ${highRiskSeen}</li>
              </ul>

              <h3 style="color: #0f172a; border-bottom: 2px solid #f1f5f9; padding-bottom: 8px; margin-top: 30px;">📅 Tomorrow's Forecast (${tomorrow})</h3>
              <p style="color: #334155;">Please prepare <strong>${totalTomorrow}</strong> physical charts for tomorrow's shifts.</p>
              <ul style="list-style: none; padding: 0; color: #334155; line-height: 1.6;">
                <li><strong>Morning Shift:</strong> ${morningTomorrow} appointments</li>
                <li><strong>Afternoon Shift:</strong> ${afternoonTomorrow} appointments</li>
              </ul>
              
              <div style="margin-top: 30px; padding: 15px; background-color: #f8fafc; border-radius: 6px; font-size: 14px; color: #64748b;">
                <p style="margin: 0;">This is an automated operational summary generated by the AR-JEN Smart Clinic System.</p>
              </div>
            </div>
          </div>
        `
      });
    }

    return NextResponse.json({ 
      success: true, 
      metrics: {
        today: { totalToday, completed, noShows, highRiskSeen },
        tomorrow: { totalTomorrow, morningTomorrow, afternoonTomorrow }
      }
    });

  } catch (error) {
    console.error('[Cron] EOD Report Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
